### ISSUE TITLE
[環境構築]絶対インポート実装

### ISSUE THREAD

**Issue by kikudesuyo** [kobatakeyann/synthetic_radar#2]
### ディレクトリ構造
- root
  - hoge
    - a.py
    - b.py
  - fuga
    - c.py
    - d.py
  
root以下から記述出来るようにする(..や.を使用しないで記述したい)

```Python
#root/hoge/a.py
def hello():
    print("hello")
```

```Python
#root/fuga/c.py
from hoge.a import hello
hello()
```

**Comment by kobatakeyann** [comment]
5faa4316025edec03bcb648dcfcffd478dbe065d
相対importを絶対importに書き換えました。
