### ISSUE TITLE
[リファクタ]api_calling.pyのファイル名の修正

### ISSUE THREAD

**Issue by kikudesuyo** [kobatakeyann/synthetic_radar#7]
- dataFetther.pyとかどうですか?
- 他にCRUD機能を追加するのであれば、もっと汎用的な名前の方がいいかな。api_service.pyとかも非常に良い名前だと思う

**Comment by kobatakeyann** [comment]
修正しました。
c60c959c279b30f47557bd024c194679a0521cf0
