### ISSUE TITLE
[提案]  helperディレクトリを作ろう

### ISSUE THREAD

**Issue by kikudesuyo** [kobatakeyann/synthetic_radar#9]
- 今各ディレクトリが横並びになっていて優劣がよく分からないから、このプロジェクトで肝となるディレクトリと、そうではなくお助けのためのサブディレクトリを瞬時に分けるために、helperディレクトリを作成してその中にサブディレクトリをぶち込んたほうが見た目がスッキリすると思う。

time_relation以外はこのプロジェクトに関わってそうだから、helper/time.pyとかにして、time.pyの中にconversion.pyのコードを各のが良さそう

**Comment by kobatakeyann** [comment]
ディレクトリ名等を変更しました。
c89ac5d57b99a3ad3a5dc2cff63c5981c03a9106
